# Generated by Django 3.2.9 on 2021-11-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articlepost_total_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
