# Generated by Django 3.2.9 on 2021-11-11 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_articlepost_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepost',
            name='comment',
        ),
    ]
